### PR TITLE
Added health handler

### PR DESCRIPTION
**Pull request by realbot**
Useful for creating health checks in plugins (I use it in https://github.com/realbot/faas-dcos)

### CODE REVIEW

**Comment by alexellis** [comment]
@realbot thank you for this idea. I think we could dig into it a little though.

I wonder if we should make this align with the K8s approach? And shouldn't this be handled by the underlying implementation which his vendoring the project?

https://github.com/openfaas/faas/pull/208/commits

**Comment by alexellis** [comment]
Let's rename to /healthz and provide a custom endpoint people can provide.

See also:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request

**Comment by johnmccabe** [comment]
Hi @realbot are you able to continue to work on this, or should someone else pick it up?

**Comment by alexellis** [comment]
@stefanprodan this is the health endpoint added by @realbot - the PR can't be merged, but I've added similar merged into master here - https://github.com/openfaas/faas-provider

**Pull request closed without merging**
